### ISSUE TITLE
The first messages gets queued but subsequent messages do not.

### ISSUE THREAD

**Issue by greergan** [briankircho/easy-amqp#1]
Unless I am doing something wrong, I am not able to send messages via routing-key. I have to send messages using the queue name instead of the routing-key.

The first messages gets queued but subsequent messages do not. After the first message is queued the following error trace is generated prior to the 2nd attempt at queuing a message.

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Connection.EventEmitter.addListener (events.js:160:15)
    at Connection.EventEmitter.once (events.js:179:8)
    at Connection.connect (/usr/local/lib/node_modules/easy-amqp/node_modules/amqp/amqp.js:1084:8)
    at Connection.reconnect (/usr/local/lib/node_modules/easy-amqp/node_modules/amqp/amqp.js:1049:8)
    at null._onTimeout (/usr/local/lib/node_modules/easy-amqp/node_modules/amqp/amqp.js:886:16)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Connection.EventEmitter.addListener (events.js:160:15)
    at Connection.EventEmitter.once (events.js:179:8)
    at Object.afterShutdown [as oncomplete](net.js:237:10)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Connection.EventEmitter.addListener (events.js:160:15)
    at Connection.connect (/usr/local/lib/node_modules/easy-amqp/node_modules/amqp/amqp.js:1083:8)
    at Connection.reconnect (/usr/local/lib/node_modules/easy-amqp/node_modules/amqp/amqp.js:1049:8)
    at null._onTimeout (/usr/local/lib/node_modules/easy-amqp/node_modules/amqp/amqp.js:886:16)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by hrizvi** [comment]
I am getting the same error now. Why its comming????
